<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    //
 /*   public $title;
    public $body;
    public $user_id;
    function __set($key, $value)
    {
        parent::__set($key, $value); // TODO: Change the autogenerated stub
    }
    function __get($key)
    {
        return parent::__get($key); // TODO: Change the autogenerated stub
    }*/
}
